#!/bin/bash
# this script should be placed in the target "OUTPUT_DIR" 
#       eg:cn96xx-release-output
#  basically, it removed all parts of a Package
#       The script is a simple script. - just modify for your use case.

BASE_DIR=/home/fsmith/marvell/sdk/SDK190603/SDK10.0_19.06.3-src
OUTPUT_DIR=$BASE_DIR/a80x0_mcbin-release-output

PACKAGE_NAME=hello_world
PACKAGE_NAME_FULL=hello_world-1.0.0

GREEN=$'\e[32m'
NORMAL=$'\e[0m'

echo $GREEN
echo "****************"
echo "before:"
echo $NORMAL 
echo "ls -la  $OUTPUT_DIR/build/$PACKAGE_NAME_FULL"
ls -la $OUTPUT_DIR/build/$PACKAGE_NAME_FULL

echo $GREEN
echo "****************"
echo "remove:"
echo $NORMAL 
echo "rm -rf $OUTPUT_DIR/build/$PACKAGE_NAME_FULL"
rm -rf $OUTPUT_DIR/build/$PACKAGE_NAME_FULL

echo $GREEN
echo "****************"
echo "after:  "
echo $NORMAL 
echo "ls -la $OUTPUT_DIR/build/$PACKAGE_NAME_FULL"
ls -la $OUTPUT_DIR/build/$PACKAGE_NAME_FULL


# look to see if Download cache location has been defined.
# if so, delete the Cache.
PKG_CACHE=$(env | grep BR2_DL_DIR )
if [ "$PKG_CACHE" != "" ] ; then  

   echo $GREEN
   echo "****************"
   echo "delete the cached downloaded: $BR2_LD_DIR/$PACKAGE_NAME"
   echo $NORMAL 
   echo "rm -rf  $BR2_LD_DIR/$PACKAGE_NAME"
   rm -rf  /sdk/BR2_LD_DIR/$PACKAGE_NAME
   echo "****************"
   echo "validate cash deleted..."
   echo "ls -la /sdk/BR2_LD_DIR/$PACKAGE_NAME"
   ls -la /sdk/BR2_LD_DIR/$PACKAGE_NAME
else
   echo $GREEN
   echo "****************"
   echo "Cached Downloads not found/used ?? "
   echo $NORMAL 
   echo "env |grep /sdk/BR2_LD_DIR  "
   echo  $PKG_CACHE
fi

echo $GREEN
echo "****************"
echo "done"
echo "****************"
echo $NORMAL 
