#! /bin/bash

# this file takes the files from the git clone process and writes the necessary files 
#   to the buildroot-external-marvell/package location.

PACKAGE_NAME=hello_world
BASE_DIR=/home/fsmith/marvell/sdk/SDK190603/SDK10.0_19.06.3

if [ -d  tmp_pkg ] ; then
  rm -rf tmp_pkg
fi


mkdir -p tmp_pkg
pushd tmp_pkg

TEST=1

if [ $TEST == 1] ; then
  wget http://10.11.65.84:80/hello_world-1.0.0.tgz
  tar -xzvf hello_world-1.0.0.tgz
else
  git clone http://github.com/fmcoatal/buildroot_hello_world
fi


#if the directory exists, delete it
if [ -d  $BASE_DIR/buildroot-external-marvell/package/$PACKAGE_NAME ] ; then
  rm -rf $BASE_DIR/buildroot-external-marvell/package/$PACKAGE_NAME
fi

# create the directory and populate the files

mkdir -p  $BASE_DIR/buildroot-external-marvell/package/$PACKAGE_NAME
cp ./package/hello_world.mk  $BASE_DIR/buildroot-external-marvell/package/$PACKAGE_NAME/.
cp ./package/Config.in  $BASE_DIR/buildroot-external-marvell/package/$PACKAGE_NAME/.


ls   $BASE_DIR/buildroot-external-marvell/package/$PACKAE_NAME/*
cat  $BASE_DIR/buildroot-external-marvell/package/$PACKAGE_NAME/Config.in
cat  $BASE_DIR/buildroot-external-marvell/package/$PACKAGE_NAME/$PACKAGE_NAME.mk


popd

echo "Done"

